//
// Created by rasmk on 20-11-2025.
//

#ifndef TRUCKINGNAVIGATION_CHECKCOORDINATESETFUNC_H
#define TRUCKINGNAVIGATION_CHECKCOORDINATESETFUNC_H
void TestConCheckCoordinateSetFunc();
#endif //TRUCKINGNAVIGATION_CHECKCOORDINATESETFUNC_H