//
// Created by steph on 09/12/2025.
//

#ifndef TRUCKINGNAVIGATION_CREATESTATICMAPFUNC_H
#define TRUCKINGNAVIGATION_CREATESTATICMAPFUNC_H

void CreateMap(int *map);

#endif //TRUCKINGNAVIGATION_CREATESTATICMAPFUNC_H