//
// Created by rasmk on 28-11-2025.
//

#ifndef TRUCKINGNAVIGATION_DEFINESCONST_H
#define TRUCKINGNAVIGATION_DEFINESCONST_H
//DEFINES OF CONSTANTS
#define DRIVINGTIMEMAX 340 //Minuts result in 13 tiels
#define DRIVINGSPEED 100 //KM per hour
#define MAPSIZE 30
#define NUMBEROFSTOPS 182
#define NUMBEROFINTERSTATESTOPS 29
#define NUMBEROFSTOPS23 123
#define NUMBEROFBLOCKADES 80

#define NORMALROAD 0
#define INTERSTATEROAD 1
#define INTERSTATESTOP 2
#define TYPE2STOP 3
#define TYPE3STOP 4
#define BLOCKADE 5
#define ROUTE 6
#define NORMALROADCOST 40
#define INTERSTATEROADCOST 24

//Errorcodes for program
#define MAPGENERROR 10
#define DESTINATIONERROR 11
#define GENINTERERROR 12
#define GENSTOPERROR 13
#define CHECKCOORDINATEERROR 14
#define BLOCKADEERROR 15

#define OUTOFBOUNDS (-1)
#define NOSPACEAVAILABLE (-2)



#endif //TRUCKINGNAVIGATION_DEFINESCONST_H