//
// Created by rasmk on 28-11-2025.
//

#ifndef TRUCKINGNAVIGATION_DEFINESCONST_H
#define TRUCKINGNAVIGATION_DEFINESCONST_H
//DEFINES OF CONSTANTS
#define DRIVINGTIMEMAX 4.5 //hours
#define DRIVINGSPEED 100 //KM per hour
#define MAPSIZE 30
#define NUMBEROFSTOPS 198
#define NUMBEROFINTERSTATESTOPS 59
#define NUMBEROFSTOPS23 139

#define NORMALROAD 0
#define INTERSTATEROAD 1
#define INTERSTATESTOP 2
#define TYPE2STOP 3
#define TYPE3STOP 4
#define BLOCKADE 5

#define NUMBEROFSTOPS 198
#define NUMBEROFINTERSTATESTOPS 59

#endif //TRUCKINGNAVIGATION_DEFINESCONST_H