//
// Created by rasmk on 20-11-2025.
//

#ifndef TRUCKINGNAVIGATION_GENBLOCKADEFUNC_H
#define TRUCKINGNAVIGATION_GENBLOCKADEFUNC_H
void TestConGenBlockadeFunc();
#endif //TRUCKINGNAVIGATION_GENBLOCKADEFUNC_H