//
// Created by rasmk on 20-11-2025.
//

#ifndef TRUCKINGNAVIGATION_GETDESTINATIONFUNC_H
#define TRUCKINGNAVIGATION_GETDESTINATIONFUNC_H
void TestConGetDestinationFunc();
#endif //TRUCKINGNAVIGATION_GETDESTINATIONFUNC_H